# Use Fedora Latest Stable
FROM registry.fedoraproject.org/fedora:43

# --- Systemd Container Standards ---
ENV container=docker
STOPSIGNAL SIGRTMIN+3

# --- Build & Runtime Dependency Installation ---
# Note: dbus-daemon is CRITICAL for systemd-networkd/machinectl interaction
RUN dnf -y --setopt=install_weak_deps=False install \
    gcc \
    make \
    binutils \
    glibc-static \
    valgrind \
    diffutils \
    systemd \
    systemd-networkd \
    systemd-resolved \
    iproute \
    iputils \
    procps-ng \
    jq \
    bash \
    kmod \
    dbus \
    dbus-daemon \
    iwd \
    hostname \
    ethtool \
    tcpdump \
    && dnf clean all

# --- Service Hygiene ---
# Remove systemd units that might conflict in a container
RUN cd /lib/systemd/system/sysinit.target.wants/ && \
    for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done && \
    rm -f /lib/systemd/system/multi-user.target.wants/* && \
    rm -f /etc/systemd/system/*.wants/* && \
    rm -f /lib/systemd/system/local-fs.target.wants/* && \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
    rm -f /lib/systemd/system/basic.target.wants/* && \
    rm -f /lib/systemd/system/anaconda.target.wants/*

# Enable core stack
RUN systemctl enable systemd-networkd systemd-resolved iwd

# --- Rocknix Directory Mimicry ---
RUN mkdir -p /storage/.config/network && \
    mkdir -p /var/lib/iwd && \
    mkdir -p /run/rocknix

CMD ["/sbin/init"]
