#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026-present Joel Wirāmu Pauling <aenertia@aenertia.net>

# -----------------------------------------------------------------------------
# FILE: sync-constants.sh
# PURPOSE: Bash-to-C Constant Synchronizer
# ARCHITECTURE: Build Tool / SSoT
#
# Parses lib/rxnm-constants.sh and generates src/rxnm_generated.h.
# This ensures the C Agent and Bash Scripts always share the same configuration.
# -----------------------------------------------------------------------------

set -u

# Paths
CONSTANTS_SH="lib/rxnm-constants.sh"
SCHEMA_JSON="api-schema.json"
HEADER_FILE="src/rxnm_generated.h"

# Validate Source
if [ ! -f "$CONSTANTS_SH" ]; then
    echo "Error: $CONSTANTS_SH not found. Run from repo root." >&2
    exit 1
fi

echo "Generating $HEADER_FILE..."

# Write Header Preamble
cat <<EOF > "$HEADER_FILE"
/* * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/sync-constants.sh
 * Source: $CONSTANTS_SH, $SCHEMA_JSON
 */

#ifndef RXNM_GENERATED_H
#define RXNM_GENERATED_H

EOF

# Function: Extract variable and write #define
extract_sh_var() {
    local var_name="$1"
    local type="$2"
    local file="$3"
    local val=""
    
    # 1. Try Standard Format: : "${VAR:=Value}"
    val=$(sed -n "s/^: \"\\\${$var_name:=\(.*\)}\"$/\1/p" "$file" | head -n1)
    
    # 2. Try Export Format: export VAR=Value
    if [ -z "$val" ]; then
        val=$(sed -n "s/^export $var_name=\(.*\)$/\1/p" "$file" | head -n1)
    fi
    
    if [ -n "$val" ]; then
        if [ "$type" == "string" ]; then
            echo "#define $var_name \"$val\"" >> "$HEADER_FILE"
        else
            echo "#define $var_name $val" >> "$HEADER_FILE"
        fi
    else
        echo "// Warning: $var_name not found in $file" >> "$HEADER_FILE"
    fi
}

echo "// --- Identity Constants ---" >> "$HEADER_FILE"
extract_sh_var "RXNM_VERSION" "string" "$CONSTANTS_SH"
extract_sh_var "DEFAULT_HOSTNAME" "string" "$CONSTANTS_SH"
echo "" >> "$HEADER_FILE"

echo "// --- Probe Targets ---" >> "$HEADER_FILE"
extract_sh_var "RXNM_PROBE_TARGETS_V4" "string" "$CONSTANTS_SH"
extract_sh_var "RXNM_PROBE_TARGETS_V6" "string" "$CONSTANTS_SH"
echo "" >> "$HEADER_FILE"

echo "// --- Path Constants ---" >> "$HEADER_FILE"
extract_sh_var "CONF_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "STATE_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "RUN_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "EPHEMERAL_NET_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "GLOBAL_LOCK_FILE" "string" "$CONSTANTS_SH"
echo "" >> "$HEADER_FILE"

echo "// --- Tuning Constants ---" >> "$HEADER_FILE"
extract_sh_var "SCAN_TIMEOUT" "int" "$CONSTANTS_SH"
extract_sh_var "CURL_TIMEOUT" "int" "$CONSTANTS_SH"
extract_sh_var "WIFI_CHANNEL_MAX" "int" "$CONSTANTS_SH"
echo "" >> "$HEADER_FILE"

echo "// --- API Schema Keys ---" >> "$HEADER_FILE"
if [ -f "$SCHEMA_JSON" ] && command -v jq >/dev/null; then
    # Extracts top-level properties as keys (KEY_SUCCESS="success", etc)
    if jq -r '.properties | keys[] as $k | "#define KEY_" + ($k | ascii_upcase) + " \"" + $k + "\""' "$SCHEMA_JSON" >> "$HEADER_FILE"; then
        echo "// Schema keys generated successfully" >> "$HEADER_FILE"
    else
        echo "Error: Failed to parse schema JSON" >&2
        # Don't fail build, just warn
        echo "#define KEY_SUCCESS \"success\"" >> "$HEADER_FILE"
    fi
else
    echo "// Warning: api-schema.json not found or jq missing. Using defaults." >> "$HEADER_FILE"
    echo "#define KEY_SUCCESS \"success\"" >> "$HEADER_FILE"
    echo "#define KEY_ERROR \"error\"" >> "$HEADER_FILE"
fi
echo "" >> "$HEADER_FILE"

echo "// --- Low Power CPU List ---" >> "$HEADER_FILE"
# Parse the massive grep regex from rxnm-constants.sh
# Looks for: grep -qEi "RK3326|..."
cpu_regex=$(grep -h "grep -qEi" "$CONSTANTS_SH" | grep "/proc/cpuinfo" | sed -n 's/.*grep -qEi "\([^"]*\)".*/\1/p')

if [ -n "$cpu_regex" ]; then
    # Convert pipes to C array format: "RK3326", "RK3566", ...
    c_list=$(echo "$cpu_regex" | sed 's/|/", "/g')
    echo "#define LOW_POWER_SOCS { \"$c_list\", NULL }" >> "$HEADER_FILE"
else
    echo "// Warning: Could not extract LOW_POWER_SOCS regex" >> "$HEADER_FILE"
    echo "#define LOW_POWER_SOCS { NULL }" >> "$HEADER_FILE"
fi

cat <<EOF >> "$HEADER_FILE"

#endif // RXNM_GENERATED_H
EOF

echo "Success: $HEADER_FILE generated."
