#!/bin/bash
# ==============================================================================
# RXNM BUILD HELPER: Constant Synchronizer
# Extracts constants from Shell Scripts and JSON Schema to generate C Headers.
# Ensures Single Source of Truth (SSoT) across Hybrid Architecture.
# ==============================================================================

# Use strict mode but allow grep/sed to fail gracefully
set -u

# Inputs
CONSTANTS_SH="lib/rxnm-constants.sh"
SCHEMA_JSON="api-schema.json"

# Output
HEADER_FILE="src/rxnm_generated.h"

# Verify inputs
if [ ! -f "$CONSTANTS_SH" ]; then
    echo "Error: $CONSTANTS_SH not found. Run from repo root." >&2
    exit 1
fi

echo "Generating $HEADER_FILE..."

# Start Header Guard
cat <<EOF > "$HEADER_FILE"
/* * AUTO-GENERATED FILE - DO NOT EDIT 
 * Generated by scripts/sync-constants.sh
 * Source: $CONSTANTS_SH, $SCHEMA_JSON
 */

#ifndef RXNM_GENERATED_H
#define RXNM_GENERATED_H

EOF

# --- PART 1: EXTRACT SHELL CONSTANTS ---
# Extraction logic using sed to parse shell defaults: : "${VAR:=VAL}"

extract_sh_var() {
    local var_name="$1"
    local type="$2" # string or int
    local file="$3"
    
    local val=""

    # 1. Try Standard Format: : "${VAR:=Value}"
    # Sed explanation: Match line starting with : "${VAR:=, capture value until }", print capture.
    val=$(sed -n "s/^: \"\\\${$var_name:=\(.*\)}\"$/\1/p" "$file" | head -n1)

    # 2. Try Export Format: export VAR=Value
    if [ -z "$val" ]; then
        val=$(sed -n "s/^export $var_name=\(.*\)$/\1/p" "$file" | head -n1)
    fi

    if [ -n "$val" ]; then
        if [ "$type" == "string" ]; then
            echo "#define $var_name \"$val\"" >> "$HEADER_FILE"
        else
            echo "#define $var_name $val" >> "$HEADER_FILE"
        fi
    else
        echo "// Warning: $var_name not found in $file" >> "$HEADER_FILE"
    fi
}

echo "// --- Path Constants (from rxnm-constants.sh) ---" >> "$HEADER_FILE"
extract_sh_var "CONF_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "STATE_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "RUN_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "EPHEMERAL_NET_DIR" "string" "$CONSTANTS_SH"
extract_sh_var "GLOBAL_LOCK_FILE" "string" "$CONSTANTS_SH"

echo "" >> "$HEADER_FILE"
echo "// --- Tuning Constants (from rxnm-constants.sh) ---" >> "$HEADER_FILE"
# Note: For adaptive constants (timeouts), this picks the first occurrence (usually the safe/slow default)
extract_sh_var "SCAN_TIMEOUT" "int" "$CONSTANTS_SH"
extract_sh_var "CURL_TIMEOUT" "int" "$CONSTANTS_SH"
extract_sh_var "WIFI_CHANNEL_MAX" "int" "$CONSTANTS_SH"

# --- PART 2: EXTRACT SCHEMA KEYS ---
# Extract top-level keys from JSON schema to ensure C code uses valid JSON keys.

echo "" >> "$HEADER_FILE"
echo "// --- API Schema Keys (from api-schema.json) ---" >> "$HEADER_FILE"

if [ -f "$SCHEMA_JSON" ] && command -v jq >/dev/null; then
    # Extract keys from properties and definitions
    # '|| true' ensures script doesn't die if jq fails
    jq -r '
        .properties | keys[] as $k | "#define KEY_" + ($k | ascii_upcase) + " \"" + $k + "\""
    ' "$SCHEMA_JSON" >> "$HEADER_FILE" || echo "// Error running jq" >> "$HEADER_FILE"
else
    echo "// Warning: api-schema.json not found or jq missing. Skipping schema keys." >> "$HEADER_FILE"
    # Fallback essential keys
    echo "#define KEY_SUCCESS \"success\"" >> "$HEADER_FILE"
    echo "#define KEY_ERROR \"error\"" >> "$HEADER_FILE"
fi

# Close Header Guard
cat <<EOF >> "$HEADER_FILE"

#endif // RXNM_GENERATED_H
EOF

echo "Success: $HEADER_FILE generated."
